### ISSUE TITLE
documentation is being clipped on small (phone) screen

### ISSUE THREAD

**Issue by koedx** [fish-shell/fish-site#110]
To reproduce the issue, navigate to a command documentation page that includes a code box example w/ lines that extend beyond the viewport width of a typical phone (code box examples reasonably disable word wrapping, but in doing so lead to a container width that exceeds the viewport of the phone screen). For example:
https://fishshell.com/docs/current/cmds/read.html 

The issue seems to originate in pydoctheme.css @ lines:555-57
```css
/* On screens that are less than 700px wide remove anything non-essential
   - the sidebar, the gradient background, ... */
@media screen and (max-width: 700px) { ...
``` 
The above media directive targets small (ie. phone) screens, & the offending style setting seems to be the "overflow: clip" style at the bottom of the css block  @ lines:590-98

```css
div#fmain {
        border-radius: 0px;
        margin: 0;
        box-shadow: 0;
        width: 100%;
        padding: 0;
        /* We have some padding/margins that would overflow - just remove it */
        overflow: clip;
    }
``` 
I'm currently overriding "overflow: clip; " using the uBlock extension's custom filter mechanism.

For anyone looking for a temporary workaround to this clipping issue, you can install uBlock & add the following filter via the extension's dashboard: fishshell.com###fmain:style(overflow: visible !important)

Viewing the site in "desktop mode" also works.

That said, having this issue w/ the above overflow setting resolved by the webmaster would be much appreciated because it makes it impossible to read the online docs on a phone w/ o having to use a workaround!

Thx 🙏 :)
